require "minitest/autorun"
require "minitest/rg"
require "sinatra/activerecord"
require_relative "../app/models/auditor.rb"
require_relative "../app/models/case.rb"
require_relative "../app/models/coordinator.rb"
require_relative "../app/models/hospital.rb"
require_relative "../app/models/patient.rb"
